name: Check and Notify for the bounties

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  alert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install Dependencies
        run: npm ci
      - name: Run Script
        run: npm run dev
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      - run: echo "Done"
